// Code generated by "stringer -type=MpcAddrType"; DO NOT EDIT.

package themis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CommonMpcAddr-0]
	_ = x[StateSubmitMpcAddr-1]
	_ = x[RewardSubmitMpcAddr-2]
}

const _MpcAddrType_name = "CommonMpcAddrStateSubmitMpcAddrRewardSubmitMpcAddr"

var _MpcAddrType_index = [...]uint8{0, 13, 31, 50}

func (i MpcAddrType) String() string {
	if i >= MpcAddrType(len(_MpcAddrType_index)-1) {
		return "MpcAddrType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MpcAddrType_name[_MpcAddrType_index[i]:_MpcAddrType_index[i+1]]
}
